services:
  nest-api:
    container_name: postgres-endpoint
    ports: 
     - 5433:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: admin
      POSTGRES_DB: mydb
    image:  postgres:16.2-alpine3.19
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/backups:/backups
      - ./db/logs:/var/log
    networks:
      - nest-api-network

  pgadmin:
      image: dpage/pgadmin4:latest
      container_name: pgadmin4
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: admin
        PGADMIN_LISTEN_PORT: 80
      ports:
        - 8080:80
      depends_on:
        - nest-api
      networks:
        - nest-api-network
networks:
  nest-api-network:
    driver: bridge
